version: '3.5'
services:
  product-service:
    depends_on:
      - mysql
    links:
      - mysql
    build: 
      context: product-service
      dockerfile: product-service/Dockerfile
    container_name: product-service
    restart: on-failure
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    networks:
      - shared-net

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    restart: always

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
    - 27017:27017

networks:
  shared-net:
    driver: bridge